CS-Worcester-CS-348-SP-2017/GitIssueActivity

LICENSE

Correct misspelling, line 671 ti -> it

---

LICENSE

changed ot->to on line 665

---

LICENSE

Corrects spelling on line 637: Changes yidfmo -> modify

---

LICENSE

misspelling, line 666 lflwoo -> follow

---

LICENSE

Correct misspelling, line 662 uyo->you

---

LICENSE

Correct misspelling, line 647: eivedcer -> received

---

LICENSE

Fix license typos

---

.project
LICENSE

Correct misspelling, line 653: elik->like

---

LICENSE

Fixed #133 line number 399 fo --> of

---

LICENSE

Fixes spelling on line 580: Changes eht -> the

---

LICENSE

change linogoaitbs->obligations on line 585

---

LICENSE

change dosnniicot->conditions on line 573

---

LICENSE

misspelling, line 567: ot -> to

---

LICENSE

Fixed #23 line 63 sihw --> wish

---

LICENSE

correct mispelling, line 44: GLP->GPL

---

LICENSE

correct mispelling, line 238: ro->or

---

LICENSE

correct spelling, line 514: propogate

---

LICENSE

Correct misspelling, line 644: NIESSTF->FITNESS

---

LICENSE

Fix license typos Issue 221

---

LICENSE

correct mispelling, line 411: illw->will

---

LICENSE

hi I made the change to the right word
